# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='articles',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 2, 7, 35, 54, 31201, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 2, 7, 36, 7, 372964, tzinfo=utc), verbose_name='修改时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='d', max_length=1, verbose_name='文章状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='tag',
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myblog.Tag', verbose_name='标签'),
        ),
    ]
